version: '3.9'

services:
  vhs-test-database:
    container_name: vhs-test-database
    image: postgres:15.1-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vhs-test-database
